pipeline {
    agent any
    tools {
        maven 'LocalMaven'
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                sh "pwd"
                sh "ls -a"
                // sh "docker build ./java-tomcat-sample-docker -t tomcatsamplewebapp:${env.BUILD_ID}"
                sh "docker build ./java-tomcat-sample-docker -t tomcatsamplewebapp"
            }
        }

        stage('Run Docker Container from build image.'){
            steps{
                sh "docker container stop webapp"
                sh "docker container rm webapp"
                sh "docker container run -d -p 9090:8080 --name webapp tomcatsamplewebapp"

            }
            
        }

    }
}